const MERCHANT_CHALLENGE_RE = /^[A-Za-z0-9_-]{16,128}$/;

/** Public, opaque identifier generated by the merchant backend for one protected action. */
export function parseMerchantChallenge(value: unknown): string | null {
  return typeof value === 'string' && MERCHANT_CHALLENGE_RE.test(value) ? value : null;
}
